_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 105
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
epochs:
    value: 10
